# Build, Test, Pack & Publish NuGet package Dimps.Extensions.Configuration.AzureTableStorage

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  slnName: 'Configuration.AzureTableStorage.sln'
  projectName: 'Dimps.Extensions.Configuration.AzureTableStorage.csproj'

steps:

- task: UseDotNet@2
  inputs:
    version: '2.2.105'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(slnName)'

- task: VSBuild@1
  inputs:
    solution: '$(slnName)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    searchPatternPack: '**/*$(projectName)'
